# Generated by Django 5.1 on 2024-09-30 13:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('avatar', models.ImageField(default='/images/avatar/avatar.png', upload_to='images/avatar/')),
                ('role', models.CharField(default='Client', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContratLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signature', models.DateField(default=datetime.datetime.now)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('pret', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('dateFin', models.DateField()),
                ('sur_commande', models.BooleanField(default=False)),
                ('dateDebut', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('Approuvee', 'Approuvee'), ('annulee', 'Annulée')], max_length=50)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.user')),
                ('nom', models.CharField(max_length=255)),
                ('numeroTel', models.CharField(max_length=30, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            bases=('db.user',),
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateTimeField(default=datetime.datetime.now)),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.contratlocation')),
                ('receveur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.user')),
            ],
        ),
        migrations.AddField(
            model_name='contratlocation',
            name='reservation',
            field=models.ManyToManyField(to='db.reservation'),
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPlaque', models.CharField(max_length=255, unique=True)),
                ('modele', models.CharField(max_length=255)),
                ('anneeAchat', models.IntegerField()),
                ('motorisation', models.CharField(max_length=255)),
                ('poids', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enlocation', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, upload_to='vehicules/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='db.marque')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.vehicule'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listesDesVehiculesFo', to='db.client'),
        ),
    ]
