# Generated by Django 5.1 on 2024-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('reservation', '0003_rename_creea_reservation_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrat',
            name='reservation',
        ),
        migrations.AddField(
            model_name='contrat',
            name='reservation',
            field=models.ManyToManyField(to='reservation.reservation'),
        ),
    ]
