# Generated by Django 5.1 on 2024-09-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contrat_reservation_contrat_reservation'),
        ('payement', '0003_rename_paiement_payement'),
        ('reservation', '0004_remove_reservation_nbrevehicules_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrat',
            new_name='ContratLocation',
        ),
    ]
