# Generated by Django 5.1 on 2024-09-28 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_rename_contrat_contratlocation'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listesDesVehiculesFournis', to='vendors.client'),
            preserve_default=False,
        ),
    ]
