# Generated by Django 5.1 on 2024-09-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_contratlocation_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratlocation',
            name='client',
        ),
    ]
