# Generated by Django 5.1 on 2024-09-28 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_contratlocation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='dateRetourVehicule',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
