# Generated by Django 5.1 on 2024-09-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_contratlocation_dateretourvehicule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratlocation',
            name='dateRetourVehicule',
        ),
    ]
