# Generated by Django 5.1 on 2024-09-30 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_remove_contratlocation_dateretourvehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratlocation',
            name='pret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contratlocation',
            name='date_signature',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
