# Generated by Django 4.2.4 on 2023-08-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorderitem',
            name='custom_order',
        ),
        migrations.AlterField(
            model_name='customorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='management.customer'),
        ),
    ]
