# Generated by Django 4.2.4 on 2023-08-08 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_customorderitem_custom_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorderitem',
            name='customerOrder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='management.customorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_Purchased', to='management.customer'),
        ),
    ]
