# Generated by Django 4.2.4 on 2023-08-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_customorderitem_customerorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderitem',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.customorder'),
        ),
    ]
