# Generated by Django 4.2.4 on 2023-08-08 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_customorderitem_customerorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorderitem',
            name='customerOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='management.customorder'),
        ),
    ]
