# Generated by Django 4.2.4 on 2023-08-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_customorderitem_customerorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='deadline',
            field=models.IntegerField(default=0),
        ),
    ]
