# Generated by Django 4.2.4 on 2023-08-15 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_customorderitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='typeOrder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomServiceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.category')),
                ('customerOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service_items', to='management.customorder')),
            ],
        ),
    ]
