# Generated by Django 4.2.4 on 2023-08-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_customorder_typeorder_customserviceorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customserviceorderitem',
            name='unit_price',
        ),
    ]
