# Generated by Django 4.2.4 on 2023-08-19 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_remove_customserviceorderitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to='management.customorder'),
        ),
    ]
