# Generated by Django 4.2.7 on 2023-11-26 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0011_alter_payment_purchase_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpurchased",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="productsProvided",
                to="management.supplier",
            ),
        ),
    ]
