# Generated by Django 4.2.7 on 2023-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0012_alter_productpurchased_supplier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productpurchased",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
