# Generated by Django 4.2.7 on 2024-01-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0013_alter_productpurchased_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorder",
            name="total_amount",
            field=models.DecimalField(decimal_places=3, max_digits=10, null=True),
        ),
    ]
