# Generated by Django 4.2.7 on 2024-02-13 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0015_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorder",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
