# Generated by Django 4.2.7 on 2024-04-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0017_alter_customorder_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customorder",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
