# Generated by Django 4.2.7 on 2024-05-09 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("management", "0018_alter_customorder_created_at"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomServiceOrderItem",
            new_name="ServiceOrderItem",
        ),
    ]
