# Generated by Django 5.1 on 2024-09-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_rename_customserviceorderitem_serviceorderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
