# Generated by Django 5.1 on 2024-09-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroPlaque', models.CharField(max_length=255, unique=True)),
                ('annee', models.IntegerField()),
                ('motorisation', models.CharField(max_length=255)),
                ('poids', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('couleur', models.CharField(max_length=255)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='vehicules/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='vehicule.marque')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
