# Generated by Django 5.1 on 2024-09-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicule',
            old_name='annee',
            new_name='anneeAchat',
        ),
    ]
