# Generated by Django 5.1 on 2024-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0002_rename_annee_vehicule_anneeachat'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='enlocation',
            field=models.BooleanField(default=True),
        ),
    ]
