# Generated by Django 5.1 on 2024-09-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicule', '0003_vehicule_enlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='enlocation',
            field=models.BooleanField(default=False),
        ),
    ]
