# Generated by Django 5.1 on 2024-09-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreVehicule', models.IntegerField()),
                ('pu', models.DecimalField(decimal_places=3, max_digits=10)),
                ('qte', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
