# Generated by Django 5.1 on 2024-09-07 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approvisionnement', '0001_initial'),
        ('vehicule', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvisionnement',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listesDesVehiculesFournis', to='vendors.fournisseur'),
        ),
        migrations.AddField(
            model_name='approvisionnement',
            name='vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vehicule.vehicule'),
        ),
    ]
