# Generated by Django 5.1 on 2024-09-17 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_initial'),
        ('payement', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paiement',
            new_name='Payement',
        ),
    ]
