# Generated by Django 5.1 on 2024-09-30 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0003_rename_paiement_payement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement',
            name='date_paiement',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
