# Generated by Django 5.1 on 2024-09-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbreVehicules', models.IntegerField()),
                ('creea', models.DateTimeField(auto_now=True)),
                ('dateFin', models.DateField()),
                ('dateDebut', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('annulee', 'Annulée')], max_length=50)),
            ],
        ),
    ]
