# Generated by Django 5.1 on 2024-09-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='creea',
            new_name='date_creation',
        ),
    ]
