# Generated by Django 5.1 on 2024-09-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_creea_reservation_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='nbreVehicules',
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
