# Generated by Django 5.1 on 2024-09-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_remove_reservation_nbrevehicules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='client',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('Approuvee', 'Approuvee'), ('annulee', 'Annulée')], max_length=50),
        ),
    ]
