# Generated by Django 5.1 on 2024-09-30 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_reservation_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='sur_commande',
            field=models.BooleanField(default=False),
        ),
    ]
